### ISSUE TITLE
Source package versions installed within `{renv}`

### ISSUE THREAD

**Issue by rpodcast** [eddelbuettel/r2u#5] opened 2022-05-26 03:28 UTC
I'm very excited for `r2u` as I've been running R on Ubuntu since the days of 8.04 Hardy Haron!

I leverage [`{renv}`](https://rstudio.github.io/renv/articles/renv.html) in almost all of my R projects. After I configured `r2u` successfully on my Ubuntu 20.04 laptop (and confirmed the binary packages installed without issue), I noticed that after bootstrapping an `{renv}` project that source versions of packages were installed after running `renv::install("name_of_package")` , which I believe is supposed to act as a shim to the default `install.packages()`. If this issue is more related to `bspm`, I'd be glad to move this over.

**Comment by eddelbuettel** [comment] 2022-05-26 11:33
That sounds like an `renv` issue to me.  Also note that the installation within RStudio's GUI 'does its own thing' and bypasses `install.packages()` and `update.packages()` meaning it cannot work with `bspm`.    CCing @enchufa2 here but I fear you may just be out of luck (and I simply will have to document this, as I should document the known `bspm` issue with the RStudio GUI).

In short, `install.packages()` and `update.packages()` are your friends.  For everything else you are on your own. 

Cool about your long Ubuntu story. Same here.  I don't actually have notes when I started / switched from Debian testing for some / most machines but I think it was also a year in and around then.

**Comment by Enchufa2** [comment] 2022-05-26 12:21
`renv` nowadays acts as a shim to `pak`, and `pak` does its own thing, it doesn't rely on `install.packages()` at all. This is unavoidable, because `install.packages()` just works with the current version of packages, and `renv` and `pak` aim at installing any archived version. So, in principle, `renv`/`pak` cannot work with `r2u` _by design_.

The issue with RStudio's GUI is not that it bypasses anything. The problem is that it calls `install.packages()` in a vanilla R session, which bypasses any `bspm` configuration (see https://github.com/Enchufa2/bspm/issues/39 and the RStudio issue referenced there).

**Comment by eddelbuettel** [comment] 2022-05-26 12:28
Thanks for additional colour.  I will leave this open til I add a line or two to the package documentation that underlies `r2u`.

**Comment by Enchufa2** [comment] 2022-05-26 12:55
And to be clear, when I said that "`renv`/`pak` cannot work with `r2u` _by design_," I meant _by design_... of `renv`/`pak`, of course.

**Comment by ginolhac** [comment] 2022-05-30 08:41
Hello,
I am also interested by the feature of having `renv` and `r2u` working together, especially in **docker**.
I tested `eddelbuettel/r2u:22.04` and it is absolutely brilliant, thanks @eddelbuettel ! Works as expected, fantastic setup.
I tried to use `renv` inside a container and this install works as it should 

```
[...]
The following package(s) will be updated in the lockfile:

# RSPM ===============================
- renv   [* -> 0.15.5]

* Lockfile written to '/test/renv.lock'.
* Project '/test' loaded. [renv 0.15.5]
* renv activated -- please restart the R session.
```

the `renv.lock` is using RSPM correctly:

```
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.15.5",
      "Source": "Repository",
      "Repository": "RSPM",
      "Hash": "6a38294e7d12f5d8e656b08c5bd8ae34",
      "Requirements": []
    }
  }
```

however, after restarting the session, any call to `renv::install()` or `install.package()` is bypassing **RSPM**.
Any idea how I should do it? I am not in RStudio GUI here and `renv` is able to register RSPM correctly before it gets activated.
Many thanks again for those great efforts.

**Comment by eddelbuettel** [comment] 2022-05-30 11:32
As we stated above, what `renv` does is outside our control.  You would have to convince its author to support `bspm` and the standard installation routines,

**Comment by ginolhac** [comment] 2022-05-30 12:01
Thanks Dirk. I have raised some concerns in August 2020 (concerning BSPM and `renv`, see https://github.com/rstudio/renv/issues/519) but apparently I was not convincing enough. In your last sentence, I guess you wanted to write "it does **not** take advantage"

**Comment by eddelbuettel** [comment] 2022-06-03 14:58
I am going to close this as it is a design choice at `renv` and not something we can do anything about, sadly.

**Closed by eddelbuettel** 2022-06-03 14:58 UTC
