### ISSUE TITLE
Can r2u handle rJava dependencies?

### ISSUE THREAD

**Issue by kendonB** [eddelbuettel/r2u#13] opened 2022-07-12 22:29 UTC
I find I need to install the dependencies listed here to get rjava working.

https://www.r-bloggers.com/2018/02/installing-rjava-on-ubuntu/

**Comment by eddelbuettel** [comment] 2022-07-12 22:43
Yes -- I also noticed the other day, cannot remember how as I don't use Java -- that the r-cran-rjava package appears to  be borked.

I have not quite decided what to do.  One easy fix may be to just force a rebuild or I could just blacklst it to depends on the distro package.

**Comment by eddelbuettel** [comment] 2022-07-12 22:44
(Forgot those articles, by the way. Most of them are crap as are the StackOverflow questions.  On Debian or Ubuntu, `sudo apt install r-cran-rjava` is generally what you want to get the package from the distro.  Here the r2u package shadows it and is borken which is not good.)

**Comment by eddelbuettel** [comment] 2022-07-12 23:55
Ok -- try now.  Both focal and jammy have a .2 version of the r-cran-rjava .deb package which per an extra rule adds the required `default-jre` package.  With `library(rJava)` works for me in a test container.

**Comment by eddelbuettel** [comment] 2022-07-13 00:18
I am going to close this as the fix was committed in https://github.com/eddelbuettel/r2u/commit/2e88de05a6dfcde1ecc274a74f96fbe5bca05043. In case this does not work for you please re-open with pertinent information to reproduce.

**Closed by eddelbuettel** 2022-07-13 00:18 UTC
