### ISSUE TITLE
Debian support 

### ISSUE THREAD

**Issue by larry77** [eddelbuettel/r2u#8] opened 2022-05-29 14:58 UTC
Hello, not an issue but rather a question : I run Debian stable on my box. Is it safe/possible for me to use r2u? How about Linux but non Ubuntu users in general? Thanks for the great effort

**Comment by eddelbuettel** [comment] 2022-05-29 17:04
This is a duplicate of #1.

**Closed by eddelbuettel** 2022-05-29 17:04 UTC

**Comment by eddelbuettel** [comment] 2022-05-29 17:06
It is an obvious question, but there are also obvious resource constraints on my part. I may try to take another stab at answering or at least mentioning this in the documentation website / FAQ section.

**Comment by eddelbuettel** [comment] 2022-05-29 17:07
And no you should not in general mix Debian and Ubuntu.  You are best adviised to back up your files from `$HOME` and other places and install freshly with Ubuntu if you want to switch.  This is also more of a general 'how do I ...' question for Ubuntu and Debian and not specific to `r2u`.

**Comment by larry77** [comment] 2022-05-29 17:11
Thanks for the answers.

**Comment by eddelbuettel** [comment] 2022-05-29 17:21
There are good solutions for Debian too  There are about 1000 packages in the distribution, containing most of the 'harder' ones and you can always build from source.

But sad;y we do not currently have something like `r2u` for Debian.  Sorry.
